title: MCEELinux Docs
description: Documentation for running Minecraft Education on Linux.
theme: just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-default-layout

url: https://mceelinux.github.io/docs

nav_enabled: true
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow-000
  important:
    title: Important
    color: blue-000
  new:
    title: New
    color: green-000
  note:
    title: Note
    color: purple-000
  warning:
    title: Warning
    color: red-000
