title: MCEELinux Docs
description: Documentation for running Minecraft Education on Linux.
theme: just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-default-layout

url: https://mceelinux.github.io/docs

nav_enabled: true
color_scheme: dark

callouts_level: loud # or quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
